---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-certs-k8c-io-v1-certificate
  failurePolicy: Fail
  name: mcertificate.kb.io
  rules:
  - apiGroups:
    - certs.k8c.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - certificates
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-certs-k8c-io-v1-certificate
  failurePolicy: Fail
  name: vcertificate.kb.io
  rules:
  - apiGroups:
    - certs.k8c.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - certificates
  sideEffects: None
