apiVersion: certs.k8c.io/v1
kind: Certificate
metadata:
  name: certificate-sample
  namespace: demo
spec:
  subject:
    organizations:
      - "dev"
      - "qa"
  commonName: localhost
  duration: "7d"
  dnsNames:
    - "dev.kubenet.com"
    - "localhost.com"
  secretRef:
    name: test-tls-local
  secretTemplate:
    labels:
      "k8c.io/secret": "tls"
  privateKey:
    algorithm: "RSA"
